config/routes.rb
CleanestCard::Application.routes.draw do
	
	root :to => 'sessions#new'
	
  get "boards/plan", :as => :plan

  get "boards/current", :as => :current

  resources :users
  resources :sessions#, :defaults => {:format => :json}, only: [:new, :create, :destroy]
  
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :assignments
  

  resources :categories, :defaults => {:format => :json}

  resources :items, :defaults => {:format => :json} do
    resources :items, :as => 'tasks', :controller => 'tasks', :defaults => {:format => :json}
  end

  post "items/:id/split", :to => "items#split", :as => :split_item

  put "items/:id/plan", :to => "items#plan"

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :taskable_id, :taskable_type, :user_id, :name, :description, :notes, :status, :order
  
  belongs_to :taskable, :polymorphic => true
  
  def self.filter_by_status(status)
  	where("status = ?", status)
  end
  
  #This method is deprecated with the polymorphic setup with taskable_id
  #def self.stand_alone_tasks
  	#where("project_id IS NULL")
  #end    
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	respond_to :html, :js, :json
	
	def index
		@item = Item.find(params[:item_id])
		@tasks = @item.tasks
		respond_with(@item, @tasks)
	end

	def show
		@item = Item.find(params[:item_id])
		@task = Item.find(params[:id])
	end

	def new
		@item = Item.find(params[:item_id])
		@task = @item.tasks.build
		respond_with(@task)
	end
	
	def edit
		#@project = Project.find(params[:project_id]) #these methods were copied from old project_tasks controller
		@task = Item.find(params[:id])
	end

	def create
		@item = Item.find(params[:item_id])
		@task = @item.tasks.build(params[:task])
		@task.save

		#location inlcuded below because of strange error
		#http://stackoverflow.com/questions/7303551/rails-respond-with-acting-different-in-index-and-create-method
		respond_with(@item, @task, :location => "")
	end
	
	def update
		#@project = Project.find(params[:project_id])
		@task = Item.find(params[:id])
		@task.update_attributes(params[:task])
		respond_with(@task)

		Item.reset_counters(params[:item_id], :tasks)
	end

	def destroy
		@task = Item.find(params[:id])
		@task.destroy
	end
	
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_new_task_card.html.erb
<li class="list-group-item" id="new-card">
	<%= form_for(@task, :remote => true) do |f| %>
	<%= f.hidden_field :status, :value => "backlog" %>
	<%= f.hidden_field :taskable_id, :value => params[:cat_id] %>
	<%= f.hidden_field :taskable_type, :value => "Category" %>

	<div class="form-group">
		<%= f.text_area :name, :rows => 3, :class => "form-control input-sm" %>
	</div>
	<%= f.submit "Add Task", :class => "btn btn-primary btn-sm" %>
	<button type="button" class="btn btn-default btn-sm cancel">Cancel</button>
	<% end %>
</li>

app/views/tasks/_task_card.html.erb
<li class="list-group-item card task">
	<span class="pull-right">Task</span>
	<h5 class="list-group-item-heading"><%= link_to task.name, task_path(task.id) %></h5>

	<small class="card-controls invisible">
		<i class="fa fa-chevron-down"></i>&nbsp;
		<%= link_to "Insert Project", new_project_path(:cat_id => cat_id), :remote => true %>&nbsp;&nbsp;&nbsp;
	</small>
	<small class="card-controls invisible">
		<i class="fa fa-chevron-down"></i>&nbsp;
		<%= link_to "Insert Task", new_task_path(:cat_id => cat_id), :remote => true %>&nbsp;&nbsp;&nbsp;
	</small>	
	<small class="card-controls invisible">
		<i class="fa fa-times"></i>&nbsp;
		<%= link_to 'Delete', task, method: :delete, :remote => true, data: { confirm: 'Are you sure?' }, :class => "delete-task-link" %>
	</small>
	
	<%= form_for task, :class => "hide", :remote => true do |f| %>
		<%= f.hidden_field :status, :value => "", :class => "status_field" %>
		<%= f.submit :class => "hide jquery_sub" %>
	<% end %>	
</li>

app/views/tasks/create.js.erb
$("#new-card").after("<%= j(render :partial => "task_card", :locals => { :task => @task, :cat_id => params[:taskable_id] }) %>");
$("#new-card").remove();

app/views/tasks/new.js.erb
$(".marked").after("<%= j(render "new_task_card") %>");