config/routes.rb
CleanestCard::Application.routes.draw do
	
	root :to => 'sessions#new'
	
  get "boards/plan", :as => :plan

  get "boards/current", :as => :current

  resources :users
  resources :sessions#, :defaults => {:format => :json}, only: [:new, :create, :destroy]
  
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :assignments
  

  resources :categories, :defaults => {:format => :json}

  resources :items, :defaults => {:format => :json} do
    resources :items, :as => 'tasks', :controller => 'tasks', :defaults => {:format => :json}
  end

  post "items/:id/split", :to => "items#split", :as => :split_item

  put "items/:id/plan", :to => "items#plan"

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_filter :signed_in_user

  respond_to :html, :js
	
  def plan 	
    #input bcat, kcat, view
    if params[:bcat]
      @bcat = params[:bcat]
    else
      @bcat = current_user.categories.first
    end

    if params[:kcat]
      @kcat = params[:kcat]
    else
      @kcat = current_user.categories.first
    end

    if params[:bcats]
      bcat_array = params[:bcats]
    else    
      bcat_array = current_user.categories.pluck("categories.id")
    end

    if params[:expand_all_field]
      expand_all = params[:expand_all_field].to_i #WOW!  I think this fixed it. Burned a few hours on this gotcha
    else
      expand_all = 0
    end

    #output @bcat, @kcat, @view, @bcards, @kcards, @categories
    @categories = current_user.categories

    #cards
    @backlog_cards = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array, :status => "backlog" })

    planned_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array, :status => "planned" })

    started_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array, :status => "started" })

    done_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array, :status => "done" })

    if expand_all == 0
      @planned_cards = planned_items
      @started_cards = started_items
      @done_cards = done_items
    else
      all_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array })
      #if @view == "tasks"
      #planned items
      planned_item_steps = []
      all_items.each do |item|
        planned_item_steps = planned_item_steps + item.steps.where({ :status => "planned" })
      end

      planned_empty_items = Item.where({ :linkable_type => "Category",
          :linkable_id => bcat_array,
          :status => "planned",
          :items_count => 0
      })

      @planned_cards = planned_empty_items + planned_item_steps #TODO: Add assigned items

      #started items
      started_item_steps = []
      all_items.each do |item|
        started_item_steps = started_item_steps + item.steps.where({ :status => "started" })
      end

      started_empty_items = Item.where({ :linkable_type => "Category",
          :linkable_id => bcat_array,
          :status => "started",
          :items_count => 0
      })

      @started_cards = started_empty_items + started_item_steps #TODO: Add assigned items

      #done items      
      done_item_steps = []
      all_items.each do |item|
        done_item_steps = done_item_steps + item.steps.where({ :status => "done" })
      end

      done_empty_items = Item.where({ :linkable_type => "Category",
          :linkable_id => bcat_array,
          :status => "done",
          :items_count => 0
      }) 

      @done_cards = done_empty_items + done_item_steps #TODO: Add assigned items
    end
    


    #respond_with() #TODO: Why is this not needed to call this action w/ ajax?

  end

  def current

    #input cat, view
    if params[:cat]
      @cat = params[:cat]
    else
      @cat = current_user.categories.first
    end

    if params[:view]
      @view = params[:view]
    else
      #@view = "projects"
      @view = "tasks"
    end

    if params[:bcats]
      bcat_array = params[:bcats]
    else    
      bcat_array = current_user.categories.pluck("categories.id")
    end

    if params[:expand_all_field]
      expand_all = params[:expand_all_field].to_i #WOW!  I think this fixed it. Burned a few hours on this gotcha
    else
      expand_all = 0
    end    

    #output @cat, @view, @cards, @categories
    @categories = current_user.categories

    #cards
    #planned_projects = Project.planned(current_user.id, @cat)
    planned_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array, :status => "planned" })

    #started_projects = Project.started(current_user.id, @cat)
    started_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array, :status => "started" })

    #done_projects = Project.done(current_user.id, @cat)
    done_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array, :status => "done" })


    if expand_all == 0
      @planned_cards = planned_items
      @started_cards = started_items
      @done_cards = done_items
    else
      all_items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array })
      #if @view == "tasks"
      #planned items
      planned_item_steps = []
      all_items.each do |item|
        planned_item_steps = planned_item_steps + item.steps.where({ :status => "planned" })
      end

      planned_empty_items = Item.where({ :linkable_type => "Category",
          :linkable_id => bcat_array,
          :status => "planned",
          :items_count => 0
      })

      @planned_cards = planned_empty_items + planned_item_steps #TODO: Add assigned items

      #started items
      started_item_steps = []
      all_items.each do |item|
        started_item_steps = started_item_steps + item.steps.where({ :status => "started" })
      end

      started_empty_items = Item.where({ :linkable_type => "Category",
          :linkable_id => bcat_array,
          :status => "started",
          :items_count => 0
      })

      @started_cards = started_empty_items + started_item_steps #TODO: Add assigned items

      #done items      
      done_item_steps = []
      all_items.each do |item|
        done_item_steps = done_item_steps + item.steps.where({ :status => "done" })
      end

      done_empty_items = Item.where({ :linkable_type => "Category",
          :linkable_id => bcat_array,
          :status => "done",
          :items_count => 0
      }) 

      @done_cards = done_empty_items + done_item_steps #TODO: Add assigned items
    end


    respond_with(@planned_cards, @started_cards, @done_cards)

  end


  private
  
    def signed_in_user
      unless signed_in?
        flash[:notice] = "Please sign in."
        redirect_to new_session_path
      end
    end
  
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_backlog_cards.html.erb
<ul class="list-group" id="column-backlog">
	<% @backlog_cards.each do |card| %>
		<%= render :partial => "items/item_card", :locals => { :item => card } %>
  	<% end %>
  	<% if @backlog_cards.count < 8 %>
  		<%= render "items/new_item_card" %>
  	<% end %>
</ul>

app/views/boards/_cards.html.erb
<ul class="list-group plannable" style="height: 750px" id="column-backlog">
	<% @backlog_cards.each do |card| %>
		<%= render :partial => "items/item_card", :locals => { :item => card, :cat_id => @bcat } %>
  	<% end %>
</ul>

app/views/boards/_done_cards.html.erb
<ul class="list-group" style="height: 250px" id="column-done">
	<% @done_cards.each do |card| %>			  
		<%= render :partial => "items/item_card", :locals => { :item => card } %>				       
  	<% end %>
</ul>

app/views/boards/_planned_cards.html.erb
<ul class="list-group" style="height: 250px" id="column-planned">
	<% @planned_cards.each do |card| %>			  
		<%= render :partial => "items/item_card", :locals => { :item => card } %>				       
  	<% end %>
</ul>

app/views/boards/_project_card.html.erb
<li class="list-group-item card project sortable" id="proj-<%= project.id %>">
	<i class="fa fa-folder-o pull-right"></i>
	<h5 class="list-group-item-heading"><%= link_to project.name, project_path(project.id) %></h5>
	<small class="card-controls invisible">
		<i class="fa fa-plus-square-o"></i>&nbsp;
		<%= link_to "Tasks", project_tasks_url(project), :remote => true , :class => "show-tasks" %>
		<a href="#" class="hide-tasks hidden">Hide Tasks</a>
		&nbsp;&nbsp;&nbsp;
	</small>
	<small class="card-controls invisible">
		<i class="fa fa-chevron-down"></i>&nbsp;
		<%= link_to "Insert Project", new_project_path(:proj_id => project.id, :cat_id => @category.id), :remote => true %>&nbsp;&nbsp;&nbsp;
	</small>
	<small class="card-controls invisible">
		<i class="fa fa-chevron-down"></i>&nbsp;
		<%= link_to "Insert Task", new_task_path(:proj_id => project.id, :cat_id => @category.id), :remote => true %>&nbsp;&nbsp;&nbsp;
	</small>	
	<small class="card-controls invisible">
		<i class="fa fa-times"></i>&nbsp;
		<%= link_to 'Delete', project, method: :delete, :remote => true, data: { confirm: 'Are you sure?' } %>
	</small>
	
	<%= form_for project, :class => "hide", :remote => true do |f| %>
		<%= f.hidden_field :status, :value => "", :class => "status_field" %>
		<%= f.submit :class => "hide jquery_sub" %>
	<% end %>	
</li>

app/views/boards/_started_cards.html.erb
<ul class="list-group" style="height: 250px" id="column-started">
	<% @started_cards.each do |card| %>			  
		<%= render :partial => "items/item_card", :locals => { :item => card } %>				       
  	<% end %>
</ul>

app/views/boards/current.html.erb
<%= render "shared/navbar" %>

<div class="container-full">

	<div class="row">
		<div class="col-md-24">
			<div class="menu">
				<div class="dropdown" style="display:inline">
					<a href="#" data-toggle="dropdown" class="menu-link">Filter</a>
					<ul class="dropdown-menu dropdown-menu-form" role="menu">
					<%= form_tag current_url, :method => 'get', :remote => true, :id => "filter-form" do %>
						<%= hidden_field_tag :expand_all_field, 0 %>
						<% @categories.each do |category| %>
							<li>
								<div class="form-group">
									<div class="checkbox">
										<label>
											<%= check_box_tag "bcats[]", category.id %><%= category.name %>
										</label>
									</div>
								</div>
							</li>
						<% end %>
						<li><%= submit_tag "Apply", :class => "apply-filter" %></li>
					<% end %>
					</ul>
				</div>
			      <div style="display: inline; padding-left: 25px">
			        <label style="font-weight: normal">
			          <%= check_box_tag "expand-all", 1, false, :id => "expand-all" %> Expand all
			        </label>
			      </div>										
				<div class="dropdown pull-right" style="width: 500px">
					<a href="#" data-toggle="dropdown" class="pull-right menu-link">Collaborators</a>
					<ul class="dropdown-menu" role="menu" id="category-users">
						<% Category.find(@cat).users.each do |user| %>
							<li class="drop-down-item"><%= user.email %></li>
						<% end %>
						<li class="drop-down-item">
							<%= form_tag('/assignments', :method => :post, :remote => true) do %>
								<%= hidden_field_tag :category_id, @cat %>
								<%= text_field_tag :email, "Enter email address", :class => "form-control" %>
							<% end %>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>		

	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
			  <div class="panel-heading" id="planned-panel-heading">
			    <h3 class="panel-title">Planned</h3>
			  </div>
			  <%= render 'planned_cards' %>
			</div>		
		</div>
		<div class="col-md-8">
			<div class="panel panel-default">
			  <div class="panel-heading" id="started-panel-heading">
			    <h3 class="panel-title">Started</h3>
			  </div>
			  <%= render 'started_cards' %>
			</div>		
		</div>		
		<div class="col-md-8">
			<div class="panel panel-default">
			  <div class="panel-heading" id="done-panel-heading">
			    <h3 class="panel-title">Done</h3>
			  </div>
			  <%= render 'done_cards' %>
			</div>		
		</div>
	</div>
	
</div>

app/views/boards/current.js.erb
$("#column-planned, #column-started, #column-done").remove();
$("#planned-panel-heading").after("<%= j(render 'planned_cards') %>");
$("#started-panel-heading").after("<%= j(render 'started_cards') %>");
$("#done-panel-heading").after("<%= j(render 'done_cards') %>");

$("#column-planned, #column-started, #column-done").addClass("actionable"); //Restores sortable functionality
$(".has-steps").removeClass("sortable"); //Prevents items with tasks (projects) from being sortable

app/views/boards/plan.html.erb
<%= render "shared/navbar" %>

<div class="container-full">

	<div class="row">
		<div class="col-md-7" id="backlog">
			<div class="menu">
				<div class="dropdown" style="display:inline">
					<a href="#" data-toggle="dropdown" class="menu-link">Filter</a>
					<ul class="dropdown-menu dropdown-menu-form" role="menu">
					<li style="padding-left: 20px">Categories:</li>
					<li class="divider"></li>
					<%= form_tag plan_url, :method => 'get', :remote => true, :id => "filter-form" do %>
						<%= hidden_field_tag :expand_all_field, 0 %>
						<% @categories.each do |category| %>
							<li>
								<div class="form-group" style="padding-left: 20px">
									<div class="checkbox">
										<label>
											<%= check_box_tag "bcats[]", category.id %><%= category.name %>
										</label>
									</div>
								</div>
							</li>
						<% end %>
						<li class="divider"></li>							
						<li style="padding-left: 20px"><%= submit_tag "Apply", :class => "apply-filter" %></li>
					<% end %>
					</ul>
				</div>
				<div id="update-multiple-menu" class="invisible" style="display:inline">
					<button type="button" class="btn btn-primary btn-xs pull-right" style="margin-right: 10px">Del</button>
					<button type="button" class="btn btn-primary btn-xs pull-right" style="margin-right: 10px">Plan</button>
					<span class="pull-right">0 Selected &nbsp;</span>
				</div>
			</div>
			<div class="panel panel-default">
			  <div class="panel-heading" id="backlog-panel-heading">
			    <h3 class="panel-title">Backlog</h3>
			  </div>
			  <%= render 'backlog_cards' %>
			</div>
		</div>
		<div class="col-md-17">
			<div class="row">
				<div class="col-md-24">
					<div class="menu">
						<div style="display: inline; padding-left: 5px">
							<label style="font-weight: normal">
								<%= check_box_tag "expand-all", 1, false, :id => "expand-all" %> Expand all
							</label>
						</div>					
						<div class="dropdown pull-right" style="width: 500px">
							<a href="#" data-toggle="dropdown" class="pull-right menu-link">Collaborators</a>
							<ul class="dropdown-menu" role="menu" id="category-users">
								<% Category.find(@kcat).users.each do |user| %>
									<li class="drop-down-item"><%= user.email %></li>
								<% end %>
								<li class="drop-down-item">
									<%= form_tag('/assignments', :method => :post, :remote => true) do %>
										<%= hidden_field_tag :category_id, @kcat %>
										<%= text_field_tag :email, "Enter email address", :class => "form-control" %>
									<% end %>
								</li>
							</ul>
						</div>						
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8">
					<div class="panel panel-default">
					  <div class="panel-heading" id="planned-panel-heading">
					    <h3 class="panel-title">Planned</h3>
					  </div>
					  <%= render 'planned_cards' %>
					</div>		
				</div>
				<div class="col-md-8">
					<div class="panel panel-default">
					  <div class="panel-heading" id="started-panel-heading">
					    <h3 class="panel-title">Started</h3>
					  </div>
					  <%= render 'started_cards' %>
					</div>		
				</div>		
				<div class="col-md-8">
					<div class="panel panel-default">
					  <div class="panel-heading" id="done-panel-heading">
					    <h3 class="panel-title">Done</h3>
					  </div>
					  <%= render 'done_cards' %>
					</div>		
				</div>
			</div>
		</div>
	</div>
	
</div>

app/views/boards/plan.js.erb
$("#column-backlog, #column-planned, #column-started, #column-done").remove();

$("#backlog-panel-heading").after("<%= j(render 'backlog_cards') %>");
$("#planned-panel-heading").after("<%= j(render 'planned_cards') %>");
$("#started-panel-heading").after("<%= j(render 'started_cards') %>");
$("#done-panel-heading").after("<%= j(render 'done_cards') %>");

$("#column-backlog, #column-planned").addClass("actionable"); //Restores sortable functionality

$('#column-backlog').perfectScrollbar(); //Restores scrollbar functionality