config/routes.rb
CleanestCard::Application.routes.draw do
	
	root :to => 'sessions#new'
	
  get "boards/plan", :as => :plan

  get "boards/current", :as => :current

  resources :users
  resources :sessions#, :defaults => {:format => :json}, only: [:new, :create, :destroy]
  
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :assignments
  

  resources :categories, :defaults => {:format => :json}

  resources :items, :defaults => {:format => :json} do
    resources :items, :as => 'tasks', :controller => 'tasks', :defaults => {:format => :json}
  end

  post "items/:id/split", :to => "items#split", :as => :split_item

  put "items/:id/plan", :to => "items#plan"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :assignments, :as => :assignable
  has_many :users, :through => :assignments
  
  #has_many :projects
  #has_many :tasks, :as => :taskable
  has_many :items, :as => :linkable
  
end

app/models/item.rb
class Item < ActiveRecord::Base
	attr_accessible :due_date, :linkable_id, :linkable_type, :name, :description,
                  :notes, :order, :priority, :status, :user_id, :item_type, :tasks_attributes

	belongs_to :linkable, :polymorphic => true, :counter_cache => true

	has_many :tasks, :as => :linkable, :class_name => "Item", :foreign_key => "linkable_id"
  has_many :splits

	accepts_nested_attributes_for :tasks, :allow_destroy => true

  after_save :update_parent


	def self.backlog(user_id, category_id)
  	Item.find_by_sql(
      ["select distinct i1.id, i1.name
      from items i1
      inner join items i2 on i1.id = i2.linkable_id and i2.linkable_type = 'Item'
      left join assignments a on i1.id = a.assignable_id and a.assignable_type = 'Item' and a.user_id = ?
      where i2.status = 'backlog'
      and i1.id not in (
        select i1.id
        from items i1
        inner join items i2 on i1.id = i2.linkable_id and i2.linkable_type = 'Item'
        where i2.status in ('planned', 'started', 'done')
      )
      and i1.linkable_id in (?)
      and i1.linkable_type = 'Category'", user_id, category_id]
    )
	end

  def self.latest_split(item_id)
    Item.find_by_sql(
      ["select i.*
      from splits s
      inner join items i on s.new_item_id = i.id
      where s.item_id = ?
      and i.status in ('planned', 'started')
      order by s.created_at DESC
      limit 1", item_id]
    )
  end


  private

    def update_parent
      if self.linkable_type == "Item"
        #self.status = "cq"
        parent_item = Item.find(self.linkable_id)

        backlog_tasks = parent_item.tasks.where({ :status => "backlog" }).count
        planned_tasks = parent_item.tasks.where({ :status => "planned" }).count
        started_tasks = parent_item.tasks.where({ :status => "started" }).count
        done_tasks = parent_item.tasks.where({ :status => "done" }).count

        if (planned_tasks + started_tasks + done_tasks) == 0 && backlog_tasks > 0
          parent_item.update_attribute(:status, "backlog")
        elsif (backlog_tasks + started_tasks + done_tasks) == 0 && planned_tasks > 0
          parent_item.update_attribute(:status, "planned")
        elsif (started_tasks + done_tasks) > 0 && (planned_tasks + started_tasks) > 0
          parent_item.update_attribute(:status, "started")
        elsif (backlog_tasks + planned_tasks + started_tasks) == 0 && done_tasks > 0
          parent_item.update_attribute(:status, "done")
        else
          #TODO: log error
        end

      end
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :signed_in_user

	respond_to :json, :html

  def index
    #category = current_user.categories.first
    #@items = category.items

    bcat_array = current_user.categories.pluck("categories.id")

    if params[:type] == 'item'
      @items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array})
    elsif params[:type] == 'task'
      @items = Item.where({ :linkable_type => "Item", :linkable_id => bcat_array})
    else #all items
      items = Item.where({ :linkable_type => "Category", :linkable_id => bcat_array})
      tasks = []
      items.each do |item|
        tasks = tasks + item.tasks
      end
      @items = items + tasks
    end

    respond_with(@items)
  end

  def show
    @item = Item.find(params[:id])
    respond_with(@item)
  end

	def new
		@item = Item.new

		respond_with(@item)
	end

	def create
		@item = Item.new(params[:item])
    category = current_user.categories.first
    #current_user is nil for some reason when calling this method from angularjs_client
    #This problem has to do with CSRF protection (see warning in console from web server)
    #The following solution seems to be working:
    #http://technpol.wordpress.com/2013/09/21/angularjs-and-rails-csrf-protection/
    @item.linkable_id = category.id if @item.linkable_id.blank?
		@item.save

		respond_with(@item)
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
    puts 'items controller called here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
    puts params[:item]

		@item = Item.find(params[:id])
		@item.update_attributes(params[:item])

    Item.reset_counters(@item.id, :tasks)

    Item.reset_counters(@item.linkable_id, :tasks) if @item.linkable_type == 'Item'

		respond_with(@item)
    #render :edit
	end

	def destroy
		@item = Item.find(params[:id])
    if @item.tasks.count > 0
      @item.tasks.each do |task|
        task.destroy
      end
    end
    @item.destroy

    	
    respond_with(@item)
  end	

  	def plan
  		item = Item.find(params[:id])
  		items_count = item.items_count
  		if items_count == nil
  			item.update_attribute(:status, params[:to])
  		elsif items_count == 0
  			item.update_attribute(:status, params[:to])
  		else
  			item.steps.each do |step|
  				step.update_attribute(:status, params[:to])
  			end
  		end
      Item.reset_counters(item.id, :steps)
  	end

    def split
      item = Item.find(params[:id])
      step = Item.find(params[:step])

      latest_split_item = Item.latest_split(item.id).first

      if !latest_split_item
        #create a split and a new project first
        @new_item = Item.create!(:linkable_id => item.linkable_id,
            :linkable_type => item.linkable_type,
            :name => item.name + " (Split)"
        )
        Split.create!(:item_id => item.id, :new_item_id => @new_item.id)
        step.update_attributes({ :linkable_id => @new_item.id, :status => 'planned' })
        respond_with(@new_item)
        Item.reset_counters(@new_item.id, :steps)
      else
        #add task to existing
        step.update_attributes({ :linkable_id => latest_split_item.id, :status => 'planned' })
      end
    end    

  	def link_items
  		Item.update_all(
  			{ :linkable_id => params[:parent_id], :linkable_type => "Item" },
  			{ :id => params[:item_ids] }
  		)
      Item.reset_counters(params[:parent_id], :steps)
  	end


    private
    
      def signed_in_user
        unless signed_in?
          flash[:notice] = "Please sign in."
          redirect_to new_session_path
        end
      end

	
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_card.html.erb
<li class="list-group-item card item sortable <%= "has-steps" if item.tasks.size > 0 %>" id="<%= item.id %>">
	<span class="pull-right"><%= check_box_tag "item_ids[]", item.id, false, :class => "select-card-checkbox" %></span>
	<h5 class="list-group-item-heading"><%= link_to item.name, edit_item_path(item.id) %></h5>

	<div>
		<% if item.tasks.size > 0 %>
			<span class="badge"><%= item.tasks.size %></span>
		<% end %>
		<small>
			<%= link_to "Expand", item_tasks_url(item), :remote => true , :class => "show-tasks-link invisible" %>
			<a href="#" class="hide-tasks hidden">Collapse</a>
			&nbsp;&nbsp;&nbsp;
		</small>		

		<small class="pull-right">
			<%= link_to 'Del', item, method: :delete, :remote => true, data: { confirm: 'Are you sure?' },
				:class => "delete-item-link invisible" %>
			&nbsp;&nbsp;
		</small>

		<small class="pull-right">
			<%= link_to "Insert Items", new_item_path, :remote => true,
				:class => "insert-items-link invisible" %>
			&nbsp;&nbsp;
		</small>
	</div>
	<div class="add-items hidden">
		<button type="button" class="btn btn-primary btn-xs link-items">Add Items (As tasks)</button>
	</div>
</li>

app/views/items/_new_item_card.html.erb
<li class="list-group-item" id="new-card">
	<%= form_for(:item, :url => "/items", :remote => true) do |f| %>
		<%= f.hidden_field :status, :value => "backlog" %>
		<%= f.hidden_field :linkable_id, :value => "" %>
		<%= f.hidden_field :linkable_type, :value => "Category" %>

		<div class="form-group">
			<%= f.text_field :name, :class => "form-control input-sm", :id => "new-item-name" %>
		</div>
		<%= f.submit "Add Item", :class => "btn btn-primary btn-sm" %>
		<button type="button" class="btn btn-default btn-sm cancel">Cancel</button>
	<% end %>
</li>

app/views/items/create.js.erb
$("#new-card").before("<%= j(render :partial => "item_card", :locals => { :item => @item }) %>");
$("#new-item-name").val("");
$("#new-item-name").focus();

//$("#new-card").remove();

//$(".marked").after("<%= j(render "new_item_card") %>");
$('#column-backlog').perfectScrollbar('update');


//Scroll down a bit if new card overflows
var backlogHeight = $("#column-backlog").height();

var newCardPosition = $("#new-card").position().top;
var newCardHeight = $("#new-card").height();
var newBottom = newCardPosition + newCardHeight;

var currentScrollTop = $("#column-backlog").scrollTop();

if (newBottom - backlogHeight > 0) {
	$('#column-backlog').scrollTop(currentScrollTop + (newBottom - backlogHeight + 20));
}

app/views/items/destroy.js.erb
$(".marked").remove();

$('#column-backlog').perfectScrollbar('update');

app/views/items/edit.html.erb
<%= render "shared/navbar" %>

<div class="container-narrow">
<%= nested_form_for(@item) do |f| %>
	<div class="row">
		<div class="col-md-24">
		
			<div id="project-name" class="project-section">
				<h3><%= f.text_field :name, :class => "form-control" %></h3>
				<p><%= f.text_field :description, :class => "form-control" %></p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-16">
		
			<div id="project-body">
				<div id="project-notes" class="project-section">
					<h5>Notes</h5>
					<p><%= f.text_area :notes, :class => "form-control", :rows => 10 %></p>
				</div>
				<div id="project-tasks" class="project-section">
					<h5>Tasks/Steps</h5>

					<table class="table" id="tasks">
						<thead>
							<tr>
								<th>Name</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<%= f.fields_for :steps, :wrapper => false do |step| %>
							<tr class="fields">
								<td><%= step.text_field :name, :class => "form-control input-sm" %></td>
								<td><%= step.link_to_remove "Del" %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
						
					<%= f.link_to_add "Add", :steps, :data => { :target => "#tasks" } %>
								
				</div>
			</div>
		
		</div>

		<div class="col-md-8">
			<div id="project-collaborators" class="project-section">
				<h5>Collaborators</h5>


				

			</div>
		</div>
	</div>
<%= f.submit %>
<% end %>
</div>

app/views/items/link_items.js.erb
//Workaround to avoid the the Template is missing error

app/views/items/new.js.erb
$(".marked").after("<%= j(render "new_item_card") %>");
$("#new-item-name").focus();


$('#column-backlog').perfectScrollbar('update');

app/views/items/plan.js.erb
//server response to prevent missing template error (workaround)

app/views/items/split.js.erb
<% if @new_item %>

	$("#column-planned").append("<%= j(render :partial => "item_card", :locals => { :item => @new_item, :cat_id => @new_item.linkable_id }) %>");

<% else %>
	//TODO: Update number of tasks on card
	console.log("new item already there")

<% end %>

$(".marked").remove();